spring:
  application:
    name: SpringAI
  ai:
    openai:
      api-key: sk-9a8856e1a552470ea3cbeeb9b3f4db9a
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        options:
          model: qwen-max-latest
          temperature: 0.7
      embedding:
        options:
          model: text-embedding-v3
          dimensions: 1024
    vectorstore:
      pinecone:
        api-key: pcsk_4wuZvE_AJw6GmknZsKA73HFyCfRGFsNioaj6WjiJun9MeH7Gjkx56ryKxK4TpB2oz7zJhX
        index-name: my-first-springai
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/itheima?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowPublicKeyRetrieval=true&allowMultiQueries=true&useServerPrepStmts=false
    username: root
    password: 123456

logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
    com.yu.springai: debug